@baseUrl = http://localhost:8082/api

### Health Check
GET {{baseUrl}}/health

### Get all comments
GET {{baseUrl}}/Comment
Accept: application/json

### Get comment by ID
@commentId = d99bdd02-fb42-4dd4-a967-878293d6e206
GET {{baseUrl}}/Comment/{{commentId}}
Accept: application/json

### Get comments by post ID
@postId = 00000000-0000-0000-0000-000000000000
GET {{baseUrl}}/Comment/post/{{postId}}
Accept: application/json

### Get comments by user ID
@userId = user123
GET {{baseUrl}}/Comment/user/{{userId}}
Accept: application/json

### Create a comment
POST {{baseUrl}}/Comment
Content-Type: application/json

{
  "content": "This is a test comment",
  "postId": "{{postId}}",
  "userId": "{{userId}}"
}

### Update a comment
PUT {{baseUrl}}/Comment/{{commentId}}
Content-Type: application/json

{
  "content": "This comment has been updated"
}

### Delete a comment
DELETE {{baseUrl}}/Comment/{{commentId}}
