apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment-service
  labels:
    app: comment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comment-service
  template:
    metadata:
      labels:
        app: comment-service
    spec:
      containers:
      - name: comment-service
        image: morrishh/babbly-comment-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: CassandraHosts
          value: "cassandra"
        - name: CassandraKeyspace
          value: "babbly_comments"
        - name: CassandraUsername
          value: "cassandra"
        - name: CassandraPassword
          value: "cassandra"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"
        - name: KAFKA_COMMENT_TOPIC
          value: "comment-events" 