apiVersion: v1
kind: Service
metadata:
  name: comment-service
  labels:
    app: comment-service
spec:
  type: ClusterIP
  ports:
  - port: 8082
    targetPort: 8082
    protocol: TCP
    name: http
  selector:
    app: comment-service 